[build]
command = "pnpm build"
publish = "dist"

[site]
bucket = "dist"

# Pages configuration
[pages]
build_output_dir = "dist"
custom_domains = ["yeahya.pages.dev"]

# The production environment configuration
[env.production]
name = "yeahya"

# Environment variables will be managed through Cloudflare Pages dashboard
[env.production.vars]
# Environment variables should be set via `wrangler secret put` command

# Preview environment (for branch deployments)
[env.preview]
name = "yeahya-preview" 