[build]
command = "pnpm build"
publish = "dist"

[site]
bucket = "dist"

# The production environment configuration
[env.production]
name = "yeahya"
routes = [
  { pattern = "yeahya.pages.dev", zone_name = "pages.dev" }
]

# Environment variables will be managed through Cloudflare Pages dashboard
[env.production.vars]
# Environment variables should be set via `wrangler secret put` command

# Preview environment (for branch deployments)
[env.preview]
name = "yeahya-preview" 