[build]
command = "pnpm build"
output_dir = "dist"

[site]
bucket = "./dist"

# The production environment
[env.production]
name = "yeahya"
workers_dev = true
route = { pattern = "yeahya.pages.dev/*", custom_domain = true }

# Environment variables will be set through wrangler secrets
[env.production.vars]
VITE_API_URL = ""
VITE_SUPABASE_URL = ""

# Preview environment (for branch deployments)
[env.preview]
name = "yeahya-preview"
workers_dev = true

[env.preview.vars]
VITE_API_URL = ""
VITE_SUPABASE_URL = "" 