[build]
command = "pnpm build"
publish = "dist"

[site]
bucket = "dist"

# The production environment
[env.production]
name = "yeahya"

# Environment variables will be set in Cloudflare Pages dashboard
[env.production.vars]
# Placeholder values - set these in Cloudflare Pages dashboard
VITE_API_URL = ""
VITE_SUPABASE_URL = ""

# Preview environment (for branch deployments)
[env.preview]
name = "yeahya-preview"

[env.preview.vars]
# Placeholder values - set these in Cloudflare Pages dashboard
VITE_API_URL = ""
VITE_SUPABASE_URL = "" 